build/Dockerfile.operator.openshift

/kind bug
The downstream build that uses this file would fail because the path the binary was built in the first stage does not match the path the second stage tried to copy it from.
n/a
I accidentally created an upstream PR first: https://github.com/nmstate/kubernetes-nmstate/pull/588
... but perhaps you'd prefer to pursue it there.

build/Dockerfile.operator.openshift: fix COPY path

---

manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml

/kind bug
Removes duplicated `certified` key in CSV, ([line #17](https://github.com/openshift/kubernetes-nmstate/blob/afa9c598cb418ec3f04929f635940bd29e1ea740/manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml#L17) and [line #26](https://github.com/openshift/kubernetes-nmstate/blob/afa9c598cb418ec3f04929f635940bd29e1ea740/manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml#L26)) which is currently causing the following error when building the bundle:
```
Image build failed. Error in plugin pin_operator_digest: while
constructing a mapping\n  in
"/tmp/tmpii4h0l34/openshift-kubernetes-nmstate-operator-bundle/manifests/kubernetes-nmstate-operator.v4.7.0.clusterservice …
```

Remove duplicated 'certified' key in CSV

---

manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml

This adds the privileged SCC for the nmstate-handler serviceaccount.
The nmstate-operator serviceaccount was not enough.
Multiple sa's can be specificed in the CSV.
>
/kind bug
```release-note
NONE
```

[CARRY] Add cluster rules for nmstate-handler sa

---

manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml

Originally I placed the nmstate-handler SA under the cluster
permission. It needed to be in the namespaced section.
>
/kind bug
```release-note
NONE
```

[CARRY] Move the nmstate-handler sa to the correct section

---

manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml

>
/kind bug
It fixes the example in the manifest. This has the side affect that one would not have to modify the spec in yaml mode when creating an instance of Kind: NMState.
As long as you don't have to click over to yaml mode and either fix the yaml, or remove the nodeSelector, it is working as it should.
```release-note
NONE
```

Bug 1918958: Fix the example NMState instance in the manifest

---

manifests/art.yaml

The CSV being generated for production builds by ART is not being released successfully because the CSV `name:` is not unique. This is because of a mismatch in the upstream CSV and the string replacement rules in art.yaml. 
re: https://projects.engineering.redhat.com/browse/CLOUDDST-8263
At a glance, it looks like this problem would also affect 4.8 and 4.9.

name replacement must exactly match string in CSV

---

manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml

﻿The OperatorHub currently assumes x86-only for any operators which do
not declare any such labels.  Declaring these explicitly should make the
current status more obvious in the code, and make it easier to correctly
add further architectures when conditions warrant.
```release-note
NONE
```

Bug 1987136: Declare supported arches in CSV

---

Makefile
hack/ocp-e2e-tests.sh
hack/ssh.sh
test/e2e/machineconfigs.yaml
test/e2e/nmstate.yaml

>
> /kind bug
Adds the ability to run e2e tests on OCP:
* Creates some machine configs required for e2e tests on OCP
* Adds a make target to run the tests (`test-e2e-ocp`)
* Allows to run the e2e tests against clusters with OVN (sets `PRIMARY_NIC=enp1s0` in this case)
* This PR is based on #198 from @cybertron. 
* As adding the machine configs for persistent-networking will be added in MCO in future, this is made as a separate commit to revert
* The env vars `IMAGE_REPO` and `KUBECONFIG` must be set anyhow, e.g.: `IMAGE_REPO=creydr KUBECONFIG=~/development/dev-scripts/ocp/ostest/auth/kubeconfig make …

Add OCP specific e2e test infra

---

bundle/manifests/nmstate-operator_v1_serviceaccount.yaml
manifests/4.8/nmstate-operator_v1_serviceaccount.yaml
manifests/4.9/nmstate-operator_v1_serviceaccount.yaml

This is no longer required[0] and may cause issues when newer versions
of the operator-sdk are used.
Note that I'm only removing back to 4.8, which is the oldest release where this is reported as a problem. I'm planning to leave 4.7 alone unless this also becomes a problem there.
0: https://github.com/operator-framework/operator-sdk/issues/5326
>
/kind bug
```release-note
Remove service account from manifests. This is no longer needed and conflicts with OLM's management of the service account.
```

Bug 2022447: Remove serviceaccount manifest

---

build/Dockerfile.operator.openshift
manifests/4.10/image-references
manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
manifests/4.10/nmstate.io_nmstates.yaml
manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml
manifests/kubernetes-nmstate-operator.package.yaml

Add OLM manifests for 4.10 release.
Addresses #218
```release-note
Add OLM manifests for 4.10 release
```
/hold until we have the merge from upstream into downstream (add new API versions, ...)

Add OLM manifests for OCP 4.10 release

---

hack/ocp-e2e-tests.sh

>
> /kind bug
When running the e2e tests against an OVN OCP cluster, some test fail. This is as some tests assume to have the primary nic (`enp2s0` in our case) to be the default gateway. In case of ovn this is not the case as ovs configures `br-ex` as the default gateway. For example:
https://github.com/openshift/kubernetes-nmstate/blob/46c014bbb2d8a551211e1bcf2dd219b6b0e96ff3/test/e2e/handler/bonding_default_interface_test.go#L49-L54
The following tests are skipped:
* 1 test in context `NodeNetworkConfigurationPolicy bonding default interface`: Actually it is the test `should successfully move default IP address on top of the bond` which is …

Skip e2e tests which are not supported on OVN

---

manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml

>
/kind bug
Fixes an JSON syntax error in the initialization resource:
```
Could not parse annotation operatorframework.io/initialization-resource as JSON:  SyntaxError: Unexpected token } in JSON at position 99
```
```release-note
none
```

Upstream: <carry>: Fix JSON error in initialization resource

---

hack/install-go.sh
manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml

Signed-off-by: Mick Tarsel <mtarsel@gmail.com>
Adds both ppc64le and s390x to 4.10 CSV to be included in operator hub.
```release-note
NONE
```

Add ppc64le and s390x to 4.10 CSV

---

build/Dockerfile.openshift

>
/kind bug
The current handler image for openshift has as base image `registry.ci.openshift.org/ocp/4.10:base`. This image does not include `microdnf`, so a build with ci-operator fails. This PR changes to use `dnf` instead.
The build for ART succeeds, as they are doing some replacement at the moment:
https://github.com/openshift/ocp-build-data/blob/4e8a5e21f0783ff0c790f2b7a298c8176fff2ad0/images/openshift-kubernetes-nmstate-handler.yml#L12-L15
I was wondering if this change should be done u/s, but I decided against, as this change should not be relevant for the u/s community as we are doing some image …

Switch to dnf in Openshift handler image

---

manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml

Signed-off-by: Muhammad Adeel <muhammad.adeel@ibm.com>
>
/kind bug
When installing operator from OperatorHub the example nmstate CR still has nodeSelector only for amd64. This PR will remove the node selector so that CR on all archs can be created with clicking Create NMstate button.
```release-note
```

UPSTREAM: <carry>: enable all archs in nmstate example CR

---

hack/ocp-e2e-tests.sh
hack/ssh-ci.sh

>
/kind bug
When running e2e tests in CI, we need to use a proxy server to ssh to the nodes. Otherwise we will get timeouts:
```
./hack/ssh.sh worker-0 -- sudo ip -d link show type bridge br10
stdout: ...
, stderr ssh: connect to host 192.168.111.23 port 22: Connection timed out
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24156/rehearse-24156-pull-ci-openshift-kubernetes-nmstate-master-e2e-sdn-ipv4/1471078781035745280/artifacts/e2e-sdn-ipv4/e2e/build-log.txt
This PR addresses it and uses the provided proxy to connect through on ssh when running in CI (env var `CI=true`).
**Special …

Add ssh proxy for e2e tests when in CI

---

manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml

Per https://bugzilla.redhat.com/show_bug.cgi?id=2039330 the
initialization resource is not actually working, and having it
present in the CSV results in a confusing button that doesn't work.
The alm-example entry still makes it easy to create the necessary
resource for the operator so this isn't a significant loss, although
it would still be nice to figure out why this isn't working. In the
meantime, let's remove it to improve the user experience.
>
/kind bug
```release-note
NONE, this was never released.
```

Bug 2039330: Remove initialization resource from CSV

---

manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml

>
/kind bug
Currently the CSVs deploymentsSpec does not contain the labels of the operator deployment. This is required, as the CNV operator checks by these labels if already a k-nmstate operator is installed in the cluster ([BZ 2030716](https://bugzilla.redhat.com/show_bug.cgi?id=2030716)). 
This PR adds the operators labels to the CSV.
It seems to be a bug in the operator-sdk to ignore the deployments labels and not add it in the CSV. I have created a PR with a fix but until this got merged and we have the latest version, we need to add them manually (instead of using the generated CSV from the bundle). …

Bug 2049142: Add operators app label in CSV

---

hack/ocp-e2e-tests-handler.sh
hack/ocp-e2e-tests-operator.sh

>
/kind bug
Currently set some env vars hard to values and ignore if the user provide alternative values. E.g. in case the user uses docker instead of podman for the image build, the IMAGE_BUILDER parameter is ignored. This PR addresses it and uses only the default values, if the values are not already set (e.g. as parameters in form of `IMAGE_BUILDER=docker make test-e2e-operator-ocp`)
-
```release-note
none
```

Bug 2052840: Do not ignore parameters for ocp tests

---

test/e2e/machineconfigs.yaml

>
/kind bug
In the nmstate-hack systemd unit, we configure the connection profiles. This should run before the ovs-configuration and reload the NWManager afterwards.
This is just needed for the e2e tests!
```release-note
NONE
```
**How to verify**:
This allows us to run the e2e tests against OVN clusters again.
1. Create a OVN cluster with dev-scripts (use `NETWORK_TYPE="OVNKubernetes"` in your config)
2. Start the e2e tests: `IMAGE_REPO=<your quay user> KUBECONFIG=<path to kubeconfig> make test-e2e-handler-ocp`
3. machineconfigs should be applied and e2e tests should start -> you should see …

Bug 2056607: Run nmstate-hack.service before ovs-configuration

---

hack/ssh-ci.sh

>
/kind bug
In dualstack envs `oc get no ${node_name} -ojsonpath='{.status.addresses[?(.type=="InternalIP")].address}` returns both IPs of the node. E.g. 
```
$ oc get no master-0.ostest.test.metalkube.org -ojsonpath='{.status.addresses[?(.type=="InternalIP")].address}
192.168.111.20 fd2e:6f44:5dd8:c956::14
```
This leads to issues in the ssh-ci.sh, as it takes then the 2nd IP as a parameter/command. 
This PR addresses it and just takes the IP displayed in `oc get node -o wide`.
Blocks https://github.com/openshift/release/pull/25547
```release-note
NONE
```

UPSTREAM: <carry>: Fix ssh-ci.sh for dualstack environments

---

hack/ocp-e2e-tests-handler.sh
hack/ocp-e2e-tests-operator.sh

Sometimes we have the e2e suites failing due to some flaky tests. This PR adds the `--flakeAttempts` parameter and reruns failed tests at a max. 5 times, so the whole suite does not fail due to a flake.

Rerun flaky e2e tests

---

manifests/4.11/kubernetes-nmstate-operator.v4.11.0.clusterserviceversion.yaml

In 36e01dcf6af51217a94c21949adbb42532d27f24 I updated the CSV files, but used the upstream handler image and namespace. This PR fixes it.

Bug 2086301: Fix 4.11 manifest to use correct handler image and namespace

---

hack/ocp-e2e-tests-handler.sh

>
> /kind bug
Currently we have the `Skip rollback e2e test` e2e test failing in 4.8 (was removed in 4.9). This PR skips it in CI, because it uses a file, which seems not to exist in the 4.8 image:
```
[rfe_id:3503][crit:medium][vendor:cnv-qe@redhat.com][level:component]rollback when an error happens during state configuration 
should rollback failed state configuration
/go/src/github.com/openshift/kubernetes-nmstate/test/e2e/handler/rollback_test.go:106
STEP: Setting bond1=bond8
STEP: Setting bridge1=br8
STEP: Getting nodes initial state
STEP: Rename vlan-filtering to vlan-filtering.bak to force failure during state configuration …
```

UPSTREAM: <carry>: Skip rollback e2e test

---

manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml

/kind bug
Adds permissions to list & get nodes to the operator SA in the CSV
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=2104938
```release-note
none
```

[release-4.10] Bug 2104938: Add node permission to CSV

---

hack/ocp-e2e-tests-handler.sh

Currently we can't merge any new PR as the e2e test `should discard disarranged parts of message and keep desired parts of message` fails due to https://bugzilla.redhat.com/show_bug.cgi?id=2111945.
As CI is blocked and we can't continue with bug fixing, we excluded this e2e test temporarily.
This commit should be reverted as soon as the BZ is fixed and the test runs on OpenShiftSDN again.
/hold to wait for @cybertron

tmp: Skip failing e2e test on OpenShiftSDN

---

manifests/art.yaml

/kind bug
Currently we see some `no channel heads (entries not replaced by another entry) found in channel "stable" of package "kubernetes-nmstate-operator"` in the operator subscriptions. This is because there are multiple candidates (msg seems to be misleading according to [this](https://coreos.slack.com/archives/C3VS0LV41/p1652446407094869) discussion.
This PR addresses it and fixes the wrong olm.skipRange replacement (in the CSV we defined it from 4.4.0, whereas ART searches for 4.3.0 and therefor doesn't get found:
https://github.com/openshift/kubernetes-nmstate/blob/539d52e66474aec3445325c23e20b8165c29ef59/manifests/4.11/kubernetes-nmstate-operator.v4.11.0.clusterserviceversion.yaml#L22
vs …

Bug 2106935: Fix OLM skiprange replacement

---

hack/ocp-e2e-tests-handler.sh
hack/ocp-e2e-tests-operator.sh

/kind bug
The ginkgo parameter `flakeAttempts` was deprecated:
```
...
You're using deprecated Ginkgo functionality:
=============================================
--flakeAttempts is deprecated, use --flake-attempts instead
```
This PR addresses it and uses the new parameter.
In addition this PR adjusts the timeout for the handler e2e tests to a bit more usable value.
```release-note
none
```

Rename deprecated flake attempts parameter

---

manifests/4.12/bundle.Dockerfile
manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
manifests/4.12/metadata/annotations.yaml

After da609f9f5 I didn't update the bundle manifests :man_facepalming:. 
This leads to rehearse failures in openshift/release/pull/30856. This PR addresses it.
In future openshift/release/pull/30856 should remind us about such issues.

Update bundle manifests after operator-sdk update to 1.22

---

build/Dockerfile.openshift
build/install-nmstate.distro.sh
build/install-nmstate.git.sh

Backporting ef5ca2fe6 to 4.11 release to fix [OCPBUGS-1719](https://issues.redhat.com/browse/OCPBUGS-1719)

[release-4.11] OCPBUGS-1719: Backport: handler: Install plugin-ovsdb

---

hack/ocp-e2e-tests-handler.sh

In #291 we skipped an permafailing e2e on OpenshiftSDN. This PR reverts it.
This PR is a reminder
/hold
until https://bugzilla.redhat.com/show_bug.cgi?id=2111945 is fixed

Reminder: Revert "tmp: Skip failing e2e test on OpenShiftSDN"

---

hack/ocp-devscripts-nm-logging.sh
hack/ocp-install-nightly-art-operators.sh

This PR adds 2 helper scripts which I used often when working with k-nmstate on OCP:
* `hack/ocp-devscripts-nm-logging.sh`: Script which captures the logs of network manager, network manager dispatcher and the entire journal logs in the background and saves them to disk. This can be helpful if some issues with NM arise and logs needs to attached to a case. In its current state, the script can only be run on the dev-script host machine.
* `hack/ocp-install-nightly-art-operators.sh`: This is an automation of https://hackmd.io/0vbbJdZ7RXem69vCWI61ug to install the latest nightly ART build of the operator bundle (in case you want to test the ART bundles in contrast to using `make …

Add helper scripts (install nightly ART operator bundles & capture NM logs)

---

controllers/handler/nodenetworkconfigurationpolicy_controller.go
docs/examples/lldp.yaml
go.mod
go.sum
hack/ocp-e2e-tests-handler.sh
pkg/nmpolicy/generate.go
pkg/nmpolicy/generate_test.go
test/doc/examples.go
test/e2e/handler/lldp_with_nmpolicy_test.go
test/e2e/handler/utils.go
test/e2e/upgrade/upgrade_test.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/types.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/lexer.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/rune.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/token.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/operations.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/filter.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/path.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/replace.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/visitor.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/walk.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/types/types.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/operations.go
vendor/github.com/nmstate/nmpolicy/nmpolicy/types/types.go
vendor/modules.txt

Backport of 
* [Add test exercising lldp configuration with nmpolicy](https://github.com/nmstate/kubernetes-nmstate/pull/1119)	
* [e2e,doc: Add LLDP example](https://github.com/nmstate/kubernetes-nmstate/pull/1122)
to fix [OCPBUGS-2925](https://issues.redhat.com/browse/OCPBUGS-2925)
Had to pick 6328502a45ef051bd975623ec3b6aceef007cf04 too, as the other commits depend on it

[release-4.11] OCPBUGS-2925: Backport lldp filtering fix

---

bundle.Dockerfile
bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
deploy/examples/nmstate.io_v1_nodenetworkconfigurationpolicy_cr.yaml
manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml

- added the ipv4 example for NodeNetworkConfigurationPolicy interface in bundle csv
- replicate the change in the manifests directory for ART
Signed-off-by: Nishant Parekh <nparekh@redhat.com>
Signed-off-by: Douglas Schilling Landgraf <dlandgra@redhat.com>
Is this a BUG FIX or a FEATURE ?:
Uncomment only one, leave it on its own line:
/kind bug
What this PR does / why we need it:
added the ipv4 example for NodeNetworkConfigurationPolicy interface in bundle csv
replicate the change in the manifests directory for ART
This change is trying to address the following CVP issue:
http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/ose-kubernetes-nmstate-operator-bundle-container-v4.12.0.202211110827.p0.gfdb8d6d.assembly.stream-1/ …

add ipv4 example to the interfaces in the alm-examples

---

deploy/examples/nmstate.io_v1_nmstate_cr.yaml
manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
manifests/bases/kubernetes-nmstate-operator.clusterserviceversion.yaml

The CVP tests are unhappy with the missing spec field, and although we don't actually need or want one let's provide something to make the check happy.
Note that the spec on NMState is largely used to control pod placement, and the default behavior is what will be wanted in the majority of cases. Setting any value on this object may result in undesirable behavior.
>
> /kind bug
```release-note
```

OCPBUGS-5124: Add empty spec to NMState CR example

---

build/Dockerfile.operator.openshift

>
/kind bug
The UI plugin manifests[1] should be added to the operator container so it will be able to deploy and reconcile the UI plugin related resources on an OpenShift cluster.
----
[1] https://github.com/openshift/kubernetes-nmstate/tree/master/deploy/openshift/ui-plugin
```release-note
Add missing COPY command for UI plugin manifests in openshift dockerfile.
```

Add UI Plugin manifests to Openshift Dockerfile

---

pkg/probe/probes.go
pkg/probe/probes_test.go
test/e2e/handler/rollback_test.go

* Probes: choose the default gw from the main routing table
The current logic relies on the first matching route entry with destination == 0.0.0.0/0, in order to find the default gateway to ping. When multiple routing table exist, we may have multiple entries with that destination, some of them may not be usable and even if they were, pinging that particular gateway doesn't assure the health of the node.
To overcome this, we narrow the filter to pick the next hop of the default route for the "main" routing table.
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
* E2E: add a test where we change the default gw for different table
We want to ensure ping still works if we change the default gateway for a routing table different from main one.
Signed-off-by: Federico Paolinelli …

[release-4.13] Jira OCPBUGS-10955: Probes: choose the default gw from the main routing table (#1153)

---

hack/ocp-rebase.sh

ocp-rebase: do not use static branch names

---

Makefile
deploy/operator/operator.yaml
hack/ocp-build-and-deploy-bundle.sh
hack/ocp-bundle-common.sh
hack/ocp-update-bundle-manifests.sh
hack/render-manifests.go
manifests/stable/manifests/image-references
manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml

>
/kind bug
kubernetes-nmstate-operator should deploy the D/S version of the console plugin image, and ART pipeline will replace the upstream image of `quay.io/nmstate/nmstate-console-plugin:release-1.0.0` with its downstream counterpart
```release-note
Integrate the ART build of nmstate-console-plugin image in the CSV
```

OPNET-261: Integrate the ART build of nmstate-console-plugin image in the manifests

---

hack/ocp-e2e-tests-handler.sh
hack/ocp-e2e-tests-operator.sh

If a test can't pass in 3 attempts we probably shouldn't consider that acceptable anyway, and 5 flakes on some longer tests causes us to exceed the timeout for CI jobs, which means we don't even attempt to run all of the tests.
>
> /kind bug
```release-note
```

UPSTREAM: <carry>: Lower flake attempts to 3

---

hack/nmstate-version.py

We frequently get asked when a given version of NMState became available and it's surprisingly difficult to determine that. This script starts at the errata tool page for the handler image and drills down to the corresponding Brew build logs to determine which NMState version shipped in a given release.

OPNET-347: UPSTREAM: <carry>: Add script for correlating NMState/OCP versions

---

hack/ocp-update-bundle-manifests.sh
pkg/probe/probes.go
pkg/probe/probes_test.go

The current code assumes that there is always a default gateway using IPv4 stack. Because of this, ping check will never succeed on a system without one, e.g. single-stack IPv6.
This patch changes the behaviour so that we will use either of IPv4 or IPv6 gateways effectively enabling IPv6-only systems.
Cherry-picks: https://github.com/openshift/kubernetes-nmstate/pull/396

UPSTREAM: <ae888af>: probe: Add support for systems without IPv4 gateway

---

hack/ocp-e2e-tests-handler.sh
hack/ocp-e2e-tests-operator.sh

After moving from Packet to OFCIR the config script got renamed. This PR fixes it.

UPSTREAM: <carry>: Fix CI SSH proxy hack

---

hack/ocp-update-bundle-manifests.sh
pkg/probe/probes.go
pkg/probe/probes_test.go

The current code assumes that there is always a default gateway using IPv4 stack. Because of this, ping check will never succeed on a system without one, e.g. single-stack IPv6.
This patch changes the behaviour so that we will use either of IPv4 or IPv6 gateways effectively enabling IPv6-only systems.
Cherry-picks: https://github.com/openshift/kubernetes-nmstate/pull/396

[release-4.12] UPSTREAM: <ae888af>: probe: Add support for systems without IPv4 gateway

---

pkg/probe/probes.go

Signed-off-by: Andreas Karis <ak.karis@gmail.com>
(cherry picked from commit 1bcf612cc6f0cb4b6ca1f3952988819a03f45c4a)
>
> /kind bug
```release-note
```

[4.12] OCPBUGS-22480: Use correct domain root-servers.net for DNS probes (#1163)

---

hack/nmstate-version.py

Since we moved to RHEL 9 in 4.14 for the container images the builds no longer show up on the RHEL 8 page. This adds logic to make sure we look in the right place based on the requested OCP version.
>
> /kind bug
```release-note
```

Handle RHEL 9-based images in nmstate-version script

---

test/e2e/handler/rollback_test.go

This PR changes the test scenario for configuring an incorrect DNS server. Instead of using a fixed `192.x.x.x` name server we are now using an IPv6 link-local address `fe80::deef:1` parametrized with a NIC name.
The reason for this change is the bug in NetworkManager that prevents rollbacks of incorrect DNS servers applied globally, i.e. not on a specific NIC. As this test explicitly tests the rollback functionality, we want it to explicitly configure a specific NIC and not a global configuration.
By using IPv6 link-local address we are ensure the configuration is applied to the NIC specified, what fulfills the requitement of our test.

[4.15] test: use IPv6 link-local DNS server (#1225)

---

test/e2e/handler/rollback_test.go

This PR changes the test scenario for configuring an incorrect DNS server. Instead of using a fixed `192.x.x.x` name server we are now using an IPv6 link-local address `fe80::deef:1` parametrized with a NIC name.
The reason for this change is the bug in NetworkManager that prevents rollbacks of incorrect DNS servers applied globally, i.e. not on a specific NIC. As this test explicitly tests the rollback functionality, we want it to explicitly configure a specific NIC and not a global configuration.
By using IPv6 link-local address we are ensure the configuration is applied to the NIC specified, what fulfills the requitement of our test.

[4.14] test: use IPv6 link-local DNS server (#1225)

---

test/e2e/handler/rollback_test.go

This PR changes the test scenario for configuring an incorrect DNS server. Instead of using a fixed `192.x.x.x` name server we are now using an IPv6 link-local address `fe80::deef:1` parametrized with a NIC name.
The reason for this change is the bug in NetworkManager that prevents rollbacks of incorrect DNS servers applied globally, i.e. not on a specific NIC. As this test explicitly tests the rollback functionality, we want it to explicitly configure a specific NIC and not a global configuration.
By using IPv6 link-local address we are ensure the configuration is applied to the NIC specified, what fulfills the requitement of our test.

[4.13] test: use IPv6 link-local DNS server (#1225)

---

test/e2e/handler/rollback_test.go

This PR changes the test scenario for configuring an incorrect DNS server. Instead of using a fixed `192.x.x.x` name server we are now using an IPv6 link-local address `fe80::deef:1` parametrized with a NIC name.
The reason for this change is the bug in NetworkManager that prevents rollbacks of incorrect DNS servers applied globally, i.e. not on a specific NIC. As this test explicitly tests the rollback functionality, we want it to explicitly configure a specific NIC and not a global configuration.
By using IPv6 link-local address we are ensure the configuration is applied to the NIC specified, what fulfills the requitement of our test.

[4.12] test: use IPv6 link-local DNS server (#1225)

---

hack/nmstate-version.py

It looks like this moved so the old path never matches.

Update Brew URL in nmstate-version

---

test/e2e/handler/nns_ovn.go

This commit changes the behaviour of the OVN bridge mapping test so that we do not require the initial state to be empty. Thanks to this we make e2e tests working correctly on machines whre OVN is already used and bridges are deployed.
Without this change the test will pass only if no OVN bridge mappings exist on the node. The assumption is quite strong and not really desired.

e2e: don't require empty starting state for bridge mappings

---

Makefile
bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
controllers/operator/nmstate_controller.go
controllers/operator/nmstate_controller_test.go
deploy/handler/operator.yaml
deploy/operator/operator.yaml
hack/render-manifests.go
manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml

Contains
* 54764880db90bcbb9cee2782126dbc73d1adb7fd
* 5f77ce980103d73b1e8eda14eb1d10add5f65a29
* 8e56abb1fc78d965470ff57b7c3396fb8cae94cb
and runs `make ocp-update-bundle-manifests`

OCPBUGS-34643: Fix monitoring for 4.17 branch

---

controllers/operator/nmstate_controller.go
deploy/handler/operator.yaml
test/e2e/operator/operator.go

/kind bug
This reverts commit e25d0bb66beda98f2fae8186810ab016eeee744e.
We should have this only merged at 4.17 when 4.16 -> 4.17 path is well tested.
Closes https://issues.redhat.com/browse/OCPBUGS-42222
```release-note
Revert openshift cert service integration
```

OCPBUGS-42222: Revert "openshift, operator: Use cert service at openshift (#1263)"

---

test/e2e/handler/metrics.go

Test platform scans all the logs and removes files that contain potential secrets. As bearer token is technically a secret, we are losing all the test logs.
This change adds `# notsecret` to the curl call so it will be ignored by the scanner.

test: add 'notsecret' keyword to the Bearer token

---

pkg/policyconditions/conditions.go

Cherry-picks 23f88ebcc2c5e66316ab076c6519a9678f112ffc

[4.16] handler: Retry nncp status updated on error

---

pkg/policyconditions/conditions.go

Cherry-picks 23f88ebcc2c5e66316ab076c6519a9678f112ffc

[4.15] handler: Retry nncp status updated on error

---

pkg/policyconditions/conditions.go

Cherry-picks 23f88ebcc2c5e66316ab076c6519a9678f112ffc

[4.14] handler: Retry nncp status updated on error

---

manifests/stable/manifests/image-references
manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml

Fix CSV validation by ART, currently failing with:
```
Bundle ose-kubernetes-nmstate-operator-bundle-container-v4.19.0.202502102307.p0.g86a8cd3.assembly.stream.el9-2 CSV metadata.name has no datestamp: kubernetes-nmstate-operator.v4.18.0
Bundle ose-kubernetes-nmstate-operator-bundle-container-v4.19.0.202502102307.p0.g86a8cd3.assembly.stream.el9-2 CSV spec.version has no datestamp: 4.18.0
```

NO-JIRA: Fix 4.19 CSV references

---

pkg/cluster/cluster.go

/kind bug
The IsOpenShift check is not robust enough, and this fork is just for openshift, so instead of try to debug all the openshift envs in the world we just harcode this at the fork.
```release-note
Force openshift check to true.
```

OCPBUGS-54372: force IsOpenShift to true

---

controllers/operator/nmstate_controller.go

/kind bug
The operator check if it has to remove old cert-manager stuff for openshift but it fails is they are not found, so it enters an Reconcile infinite loop.
This change just fail if there is an error but is different that NotFound.
Backport from upstream of:
- https://github.com/nmstate/kubernetes-nmstate/pull/1302
```release-note
Continue on cleanup NotFound errors
```

[release-4.18]: operator, Continue on cleanup NotFound errors (#1302)

---

test/e2e/handler/simple_bridge_and_bond_test.go

Looks like when disabling vlan filtering the bridge vlan show command is not working as expected but the system is correctly working, this change just check tha vlan filtering is 0 at the bridge and that the default pvid is 1, that's more than enough.
Cherry-pick from https://github.com/nmstate/kubernetes-nmstate/pull/1279
```release-note
NONE
```

[release-4.18] e2e, handler: Simplify vlan_filtering 0 check (#1279)

---

pkg/nmstatectl/nmstatectl.go

Enable debug logging of nmstate apply, this could help developer to debug issue when something broken.
Cherry-pick from https://github.com/nmstate/kubernetes-nmstate/pull/1294
```release-note
Use verbose mode for nmstatectl apply
```

[release-4.18] Enable debug logging of nmstate apply (#1294)

---

hack/ocp-bundle-common.sh

version starts with `v` now
```shell
+ yq4
+ VERSION_REGEX=' version v?4\.[0-9]+\.[0-9]$'
++ yq --version
+ [[ yq 3.4.3 =~  version v?4\.[0-9]+\.[0-9]$ ]]
++ pwd
+ INSTALL_DIR=/home/bob/kubernetes-nmstate/build/_output/bin
+ [[ -f /home/bob/kubernetes-nmstate/build/_output/bin/yq ]]
++ /home/bob/kubernetes-nmstate/build/_output/bin/yq --version
+ [[ yq (https://github.com/mikefarah/yq/) version v4.35.2 =~  version v?4\.[0-9]+\.[0-9]$ ]]
+ echo /home/bob/kubernetes-nmstate/build/_output/bin/yq
```
/kind bug
Reduces build noise.  `yq4` will re-run go install every time.
```release-note
Fixed yq4 version check regex.
```

deps: fix yq version v4.35.2 regex

---

Makefile
manifests/stable/bundle.Dockerfile
manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
manifests/stable/metadata/annotations.yaml

Some changes from
https://github.com/nmstate/kubernetes-nmstate/pull/1335 got lost during the automatic rebase proces. Mainly due to the fact that we have lots of downstream-only commits and the git history is a bit of a mess.
This commit brings back missing changes.

UPSTREAM<carry>: makefile: manually bring changes from #1335 upstream

---

hack/ocp-bundle-common.sh

This PR adds a missing `MANIFESTS_DIR` variable which was defined in Makefile but not in the OCP common script.
This is needed because there are cases where ocp-update-bundle-manifest is run directly as a script and not via make target (e.g. when rebasebot runs in a non-interactive mode).

UPSTREAM: <carry>: Fix adding network policy to OLM bundle

---

Makefile

>
/kind bug
Same as in upstream, but downstream we have another target that needs some modification. (After porting k-nmstate to Darwin I cleaned up the checks for bundle change and manifest change. In a copy paste mistake I included the keyword bundle to the git diff which caused the exit code to not indicate a bundle change even when it did change.)
```release-note
NONE
```

NO-ISSUE: make target for check ocp-bundle would not indicate a change in bundle.

---

pkg/nmstatectl/nmstatectl.go

Revert "Enable debug logging of nmstate apply (#1294)". This reverts commit c8e67f84ad940b8d699590c71ba71085c9f30699.
Fixes: OCPBUGS-60452

OCPBUGS-60452: Revert deadlock introduced by verbose output

---

controllers/operator/nmstate_controller.go

Manually pick #1357 to 4.19. Earlier releases are not needed because this code was heavily refactored and in 4.18 looked completely different.

[4.19] operator: use strategic merge to prevent losing labels
