openshift/kubernetes-nmstate

- OWNERS
Adding BZ details to OWNERS file is ART requirement.
```release-note
```
> Update BZ details in OWNERS file

- OWNERS
>
> /kind bug
```release-note
NONE
```
> Update component and subcomponents for BZ in OWNERS file

- OWNERS
>
> /kind bug
To expedite midstream patches, add some additional reviewers and approvers.
```release-note
NONE
```
> [CARRY] Add midstream reviewers and approvers

- build/Dockerfile.operator.openshift
- manifests/4.7/image-references
- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
- manifests/4.7/nmstate-operator_v1_serviceaccount.yaml
- manifests/4.7/nmstate.io_nmstates.yaml
- manifests/art.yaml
- manifests/kubernetes-nmstate-operator.package.yaml
- metadata/annotations.yaml
>
> /kind bug
```release-note
NONE
```
> [CARRY] Make operator bundle for OLM

- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
Inadverdently used 'RELATED_IMAGES_' instead of 'RELATED_IMAGE_'
>
/kind bug
```release-note
NONE
```
> [CARRY] Correct the env var used for the handler image

- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
>
/kind bug
```release-note
NONE
```
> [CARRY] Add securitycontextconstraints to CSV

- bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
- controllers/nmstate_controller.go
- controllers/nmstate_controller_test.go
- deploy/operator/operator.yaml
- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
This is causing a conflict with ART tooling.
>
/kind bug
```release-note
NONE
```
> [CARRY] Remove RELATED_IMAGE_ from the handler image env var

- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
The example as given doesn't really work. It's better to have a working
sample.
>
/kind bug
```release-note
As of now, the NMStates instance must be named "nmstate"
```
> Change example name to nmstate, and add nodeSelector

- manifests/4.8/image-references
- manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
- manifests/4.8/nmstate-operator_v1_serviceaccount.yaml
- manifests/4.8/nmstate.io_nmstates.yaml
>
> /kind bug
Adds the manifests for OpenShift 4.8
```release-note
NONE
```
> Add manifests for 4.8

- build/Dockerfile.operator.openshift
- manifests/4.9/image-references
- manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml
- manifests/4.9/nmstate-operator_v1_serviceaccount.yaml
- manifests/4.9/nmstate.io_nmstates.yaml
Part of [ART-2868](https://issues.redhat.com/browse/ART-2868), update CSV channels to be able to re-enable automated builds for this image.
> release-4.9-olm-manifests

- manifests/kubernetes-nmstate-operator.package.yaml
> Set default bundle channel to 4.9

- Makefile
**Is this a BUG FIX or a FEATURE ?**: 
>
/kind bug
**What this PR does / why we need it**: The manifests target in the Makefile is currently broken because we added a manifests directory. This fixes "make manifests" so it works correctly.
```release-note
NONE
```
> UPSTREAM: <carry>: Add manifests to .PHONY in Makefile

- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
- manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
- manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml
- manifests/art.yaml
/kind bug
The olm.skipRange replacement in art,yml is currently a noop. This should fix that.
```release-note
NONE
```
> Bug 1994991: Fix skipRange replacement

- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
- manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
- manifests/art.yaml
/kind bug
olm.skipRange is not correctly set in product builds.
```release-note
NONE
```
> Bug 1995471: Fix skip range 4.8

- build/Dockerfile.openshift
U/s has removed the build/bin directory, do not attempt to copy
it anymore.
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
>
/kind bug
```release-note
NONE
```
> Sync Dockerfile.openshift with u/s

- manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
- manifests/art.yaml
/kind bug
olm.skipRange is not correctly substituted and set
```release-note
NONE
```
> Bug 1995506: Fix olm.skipRange substitution 4.7

- manifests/art.yaml
align the correct image name
>
/kind bug
currently the image name is kubernetes-nmstate-operator
```release-note
NONE
```
> update naming convention

- manifests/art.yaml
>
/kind bug
currently the image name is kubernetes-nmstate-operator, need to align the correct image name
```release-note
```
> update naming convention for 4.9

- bundle/manifests/nmstate-operator_v1_serviceaccount.yaml
- manifests/4.8/nmstate-operator_v1_serviceaccount.yaml
This is no longer required[0] and may cause issues when newer versions
of the operator-sdk are used.
0: https://github.com/operator-framework/operator-sdk/issues/5326
>
> /kind bug
```release-note
```
> Bug 2023529: [release-4.8] Remove serviceaccount manifest

- manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>
**What this PR does / why we need it**: adds arm64 to the CSV
```release-note
```
> UPSTREAM: <carry>: add arm64 to 4.10 CSV

- bundle/manifests/nmstate-operator_v1_serviceaccount.yaml
- manifests/4.7/nmstate-operator_v1_serviceaccount.yaml
This is no longer required[0] and may cause issues when newer versions
of the operator-sdk are used.
0: https://github.com/operator-framework/operator-sdk/issues/5326
>
> /kind bug
```release-note
```
> Bug 2027793: [release-4.7] Remove serviceaccount manifest

- manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Per [0]. This allows filtering of operators in OperatorHub based on
the ability to run in a disconnected environment.
0: https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs
>
> /kind bug
```release-note
NONE
```
> UPSTREAM: <carry>: Add disconnected annotation for OperatorHub

- OWNERS
Toni is no longer working on this project so it doesn't make sense
to have him listed as a reviewer. Adding Christoph since he has done
quite a bit of work on the project lately.
>
> /kind bug
```release-note
NONE
```
> UPSTREAM: <carry>: Update OWNERS

- manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml
Just applying #247 to the 4.9 manifests too since it merged before
I could update it.
>
/kind bug
```release-note
NONE
```
> Remove initialization resource from 4.9 too

- manifests/4.11/image-references
- manifests/4.11/kubernetes-nmstate-operator.v4.11.0.clusterserviceversion.yaml
- manifests/4.11/nmstate.io_nmstates.yaml
- manifests/kubernetes-nmstate-operator.package.yaml
>
> /kind bug
Add manifests for 4.11
```release-note
Add manifests for 4.11
```
> UPSTREAM: <carry>: Add manifests for 4.11

- manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
- manifests/4.11/kubernetes-nmstate-operator.v4.11.0.clusterserviceversion.yaml
>
/kind bug
Need to add the qos class and priority class to the template of the operator in the CSV file.
```release-note
none
```
> Bug 2046191: Add qos class and priority class to operator template in CSV

- manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Backport of #267 to 4.10 release
> [release-4.10] Bug 2059095: Add qos class and priority class to operator template in CSV

- manifests/4.11/kubernetes-nmstate-operator.v4.11.0.clusterserviceversion.yaml
Adds the securitycontextconstaint to the rules in the CSV.
> Bug 2086301: Fix SCC rules in 4.11 CSV

- manifests/4.11/nmstate.io_nmstates.yaml
Syncing the NMState CRD with the code base
> Bug 2089163: Update bundle NMState CRD to be in sync with code base

- developing-on-ocp.md
Adds a readme with some helpful steps when developing for / on OpenShift.
> Add readme for developing for OCP

- hack/ocp-rebase.sh
This PR adds a script which automates most of the steps required to rebase up upstream. It has it steps from https://github.com/openshift/kubernetes-nmstate/pull/298.
> Add helper script for rebasing

- hack/ocp-rebase.sh
Helps identify the author of cherry-pick/rebase
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
> ocp-rebase: use -s in cherry-pick

- hack/ocp-rebase.sh
This patch adds the following suggestions:
- remote trees (upstream/downstream)
- last rebase commit id
- upstream/downstrea branches
Now the maintainers can only run the script
and rebase should happen much more easily.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
> ocp-rebase: general improvements

- Makefile
- makefile: add more verbosity
- makefile: breaking long lines
> makefile: general improvements

- go.mod
- go.sum
- vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
- vendor/github.com/Masterminds/goutils/randomstringutils.go
- vendor/github.com/Masterminds/goutils/stringutils.go
- vendor/modules.txt
master commid-id: 0372c67802c9d12933d36dd54a7013d0d6ec31ae
Signed-off-by: Petr Horacek <hrck@protonmail.com>
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
> OCPBUGS-8441: UPSTREAM <carry>: Update goutils dependency to v1.1.1 (#1140)

- go.mod
- go.sum
- vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
- vendor/github.com/Masterminds/goutils/randomstringutils.go
- vendor/github.com/Masterminds/goutils/stringutils.go
- vendor/modules.txt
master commid-id: 0372c67802c9d12933d36dd54a7013d0d6ec31ae
Signed-off-by: Petr Horacek <hrck@protonmail.com>
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
> OCPBUGS-8440: UPSTREAM: <carry>: Update goutils dependency to v1.1.1

- hack/ocp-e2e-tests-handler.sh
- hack/ocp-e2e-tests-operator.sh
- hack/ocp-update-bundle-manifests.sh
Cherry-picks: https://github.com/openshift/kubernetes-nmstate/pull/423
> [release-4.12] UPSTREAM: <carry>: Fix CI SSH proxy hack

- hack/ocp-e2e-tests-handler.sh
- hack/ocp-e2e-tests-operator.sh
Cherry-picks: https://github.com/openshift/kubernetes-nmstate/pull/423
> [release-4.11] UPSTREAM: <carry>: Fix CI SSH proxy hack

- pkg/webhook/nodenetworkconfigurationpolicy/server.go
/kind bug
```release-note
NONE
```
> [4.15] OCPBUGS-22203: webhook: disable HTTP2 to avoid CVE-2023-39325

- manifests/bases/kubernetes-nmstate-operator.clusterserviceversion.yaml
- manifests/kubernetes-nmstate-operator.package.yaml
- manifests/stable/manifests/image-references
- manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
>
> /kind bug
```release-note
```
> OCPBUGS-21946: Bump manifest versions to 4.15

- OWNERS
He's no longer working on the project so there's no sense having the bot autoassign him.
>
> /kind bug
```release-note
```
> Remove Doug from OWNERS

- .snyk
These files either come from other projects or are not used in production so there's no reason to security scan them.
>
> /kind bug
```release-note
```
> OCPBUGS-26766: Add .snyk file to ignore vendor and test files

- manifests/bases/kubernetes-nmstate-operator.clusterserviceversion.yaml
- manifests/kubernetes-nmstate-operator.package.yaml
- manifests/stable/manifests/image-references
- manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
>
> /kind bug
```release-note
```
> OCPBUGS-28780: Bump manifest versions to 4.16

- hack/ssh-ci.sh
> UPSTREAM: <carry>: Add custom ssh port for CI servers

- deploy/openshift/ui-plugin/consoleplugin.yaml
>
> /kind bug
ConsolePugin v1 is supported from 4.12 and higher so no worries
backport https://github.com/nmstate/kubernetes-nmstate/pull/1251
```release-note
```
> Backport #1251 to 4.16

- README.md
Manually mangling history. Creating a fake merge commit with 2 parents, 43793e0f and db5c1b55 with the hope that rebasebot picks it as "its own" and continue rebasing.
We are currently missing 3 commits from upstream, 
* https://github.com/nmstate/kubernetes-nmstate/commit/a12e1f72fc18825e288579bc18dc619838bce0b1
* https://github.com/nmstate/kubernetes-nmstate/commit/c209ed91759d2424a009fe18d014d81e0a48e4a0
* https://github.com/nmstate/kubernetes-nmstate/commit/1e93382cfb6a53d46aba4785c194a03c4b75c994
> Fix rebasebot by manual merge commit

- controllers/operator/nmstate_controller.go
- deploy/handler/operator.yaml
- test/e2e/operator/operator.go
Manual cherry-pick of https://github.com/nmstate/kubernetes-nmstate/pull/1263 into 4.16 release
> [4.16] openshift, operator: Use cert service at openshift

- pkg/policyconditions/conditions.go
Cherry-picks 23f88ebcc2c5e66316ab076c6519a9678f112ffc
> [4.17] handler: Retry nncp status updated on error

- controllers/operator/nmstate_controller.go
- controllers/operator/nmstate_controller_test.go
- deploy/handler/operator.yaml
- test/e2e/operator/operator.go
Cherry-picks
1) 1e93382cfb6a53d46aba4785c194a03c4b75c994
2) 01d3b4f2b41c19df9d55b57c407bbf1a7312ba70
3) 8506e7b6adcf440a5b0f8bfa0a9fca500b812452
> [4.17] Use cert service

- controllers/operator/nmstate_controller.go
- controllers/operator/nmstate_controller_test.go
- deploy/handler/operator.yaml
- test/e2e/operator/operator.go
Cherry-picks
1) 1e93382cfb6a53d46aba4785c194a03c4b75c994
2) 01d3b4f2b41c19df9d55b57c407bbf1a7312ba70
3) 8506e7b6adcf440a5b0f8bfa0a9fca500b812452
> [4.16] Use cert service

- deploy/handler/operator.yaml
> [4.18] Mount OVS directory instead of socket file

- deploy/handler/operator.yaml
> [4.17] Mount OVS directory instead of socket file

- deploy/handler/operator.yaml
> [4.16] Mount OVS directory instead of socket file

- api/v1/nmstate_types.go
- bundle/manifests/nmstate.io_nmstates.yaml
- controllers/operator/nmstate_controller.go
- deploy/crds/nmstate.io_nmstates.yaml
- deploy/openshift/ui-plugin/deployment.yaml
- manifests/stable/manifests/nmstate.io_nmstates.yaml
This is a manual cherry-pick of #561
>
> /kind bug
```release-note
NONE
```
> [release-4.16] OCPBUGS-50627: Allow configuring node placement for nmstate-console-plugin

- automation/check-patch.setup.sh
- hack/sanitized-xtrace.sh
>
> /kind bug
```release-note
```
> ci: Sanitize secrets

- deploy/openshift/ui-plugin/deployment.yaml
- test/e2e/operator/operator.go
>
> /kind bug
```release-note
```
> OCPBUGS-54295: e2e, operator, Check console plugin deployment

- test/e2e/handler/metrics.go
>
> /kind bug
```release-note
```
> [release-4.18] adapt test to notsecret

- OWNERS
>
> /kind bug
As part of my onboarding process I was tasked with adding myself as reviewer.
```release-note
NONE
```
> NO-JIRA: Add emy as reviewer in the owners file

- hack/ocp-update-bundle-manifests.sh
> UPSTREAM: <carry>: Hold network policy in the OLM bundle

- test/e2e/handler/nns_ovn.go
- test/e2e/handler/states.go
Manually cherry-pick #1354 to 4.18; without this the CI is broken due to the missing functionality
> [4.18] test: define ovs-bridge in the bridge-mappings test
